#!/bin/bash

cp $HOME/.inputrc .inputrc
cat $HOME/.gitconfig | grep -v smtp > .gitconfig
cp $HOME/.tmux.conf .tmux.conf
cp $HOME/.config/fish/config.fish .config/fish
cat $HOME/.profile | grep -v AWS > .profile
cp $HOME/tools/tm tools/tm

